# Generated by Django 4.2.5 on 2023-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitap', '0002_delete_kitap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('yazar', models.CharField(max_length=150)),
                ('sayfa_sayisi', models.IntegerField(verbose_name='Sayfa Sayısı')),
                ('yayin_evi', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
