# Generated by Django 4.2.5 on 2023-09-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitap',
        ),
    ]
